In [ ]:
a_list =[]
for i in range(5):
    a_list.append(int(input()))
print(a_list)

In [2]:
file_path = "resources/test_stitch/merge_0101.stl"

original_file_name= file_path.split("/")[-1]
original_file_name = original_file_name.split(".")[0]

print(original_file_name)

merge_0101


In [1]:
import numpy as np

# Translation values
tx, ty, tz = -6.98707515, -0.63889001, 1.01351335

# Translation matrix
T = np.array([
    [1, 0, 0, tx],
    [0, 1, 0, ty],
    [0, 0, 1, tz],
    [0, 0, 0, 1]
])

print("平移矩陣:")
print(T)

平移矩陣:
[[ 1.          0.          0.         -6.98707515]
 [ 0.          1.          0.         -0.63889001]
 [ 0.          0.          1.          1.01351335]
 [ 0.          0.          0.          1.        ]]
